# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartForm(object):
    def setupUi(self, StartForm):
        StartForm.setObjectName("StartForm")
        StartForm.resize(625, 493)
        self.verticalLayout = QtWidgets.QVBoxLayout(StartForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(StartForm)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 588, 322))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Image.setMinimumSize(QtCore.QSize(0, 0))
        self.Image.setText("")
        self.Image.setObjectName("Image")
        self.horizontalLayout.addWidget(self.Image)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        spacerItem = QtWidgets.QSpacerItem(0, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ChooseBtn = QtWidgets.QPushButton(StartForm)
        self.ChooseBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.ChooseBtn.setObjectName("ChooseBtn")
        self.horizontalLayout_3.addWidget(self.ChooseBtn)
        self.NextBtn = QtWidgets.QPushButton(StartForm)
        self.NextBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.NextBtn.setObjectName("NextBtn")
        self.horizontalLayout_3.addWidget(self.NextBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(StartForm)
        QtCore.QMetaObject.connectSlotsByName(StartForm)

    def retranslateUi(self, StartForm):
        _translate = QtCore.QCoreApplication.translate
        StartForm.setWindowTitle(_translate("StartForm", "Form"))
        self.ChooseBtn.setText(_translate("StartForm", "Choose File"))
        self.NextBtn.setText(_translate("StartForm", "Next"))
