# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartForm(object):
    def setupUi(self, StartForm):
        StartForm.setObjectName("StartForm")
        StartForm.resize(625, 493)
        self.verticalLayout = QtWidgets.QVBoxLayout(StartForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(StartForm)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 588, 304))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Image.setMinimumSize(QtCore.QSize(0, 0))
        self.Image.setText("")
        self.Image.setObjectName("Image")
        self.horizontalLayout.addWidget(self.Image)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.Sigma = QtWidgets.QLabel(StartForm)
        self.Sigma.setAlignment(QtCore.Qt.AlignCenter)
        self.Sigma.setObjectName("Sigma")
        self.verticalLayout.addWidget(self.Sigma)
        self.SigmaVal = QtWidgets.QSlider(StartForm)
        self.SigmaVal.setMinimumSize(QtCore.QSize(0, 0))
        self.SigmaVal.setMinimum(1)
        self.SigmaVal.setMaximum(1000)
        self.SigmaVal.setProperty("value", 10)
        self.SigmaVal.setOrientation(QtCore.Qt.Horizontal)
        self.SigmaVal.setObjectName("SigmaVal")
        self.verticalLayout.addWidget(self.SigmaVal)
        self.Size = QtWidgets.QLabel(StartForm)
        self.Size.setAlignment(QtCore.Qt.AlignCenter)
        self.Size.setObjectName("Size")
        self.verticalLayout.addWidget(self.Size)
        self.SizeVal = QtWidgets.QSlider(StartForm)
        self.SizeVal.setMinimum(0)
        self.SizeVal.setMaximum(10)
        self.SizeVal.setProperty("value", 2)
        self.SizeVal.setOrientation(QtCore.Qt.Horizontal)
        self.SizeVal.setObjectName("SizeVal")
        self.verticalLayout.addWidget(self.SizeVal)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BackBtn = QtWidgets.QPushButton(StartForm)
        self.BackBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.BackBtn.setObjectName("BackBtn")
        self.horizontalLayout_3.addWidget(self.BackBtn)
        self.GoBtn = QtWidgets.QPushButton(StartForm)
        self.GoBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.GoBtn.setObjectName("GoBtn")
        self.horizontalLayout_3.addWidget(self.GoBtn)
        self.NextBtn = QtWidgets.QPushButton(StartForm)
        self.NextBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.NextBtn.setObjectName("NextBtn")
        self.horizontalLayout_3.addWidget(self.NextBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(StartForm)
        QtCore.QMetaObject.connectSlotsByName(StartForm)

    def retranslateUi(self, StartForm):
        _translate = QtCore.QCoreApplication.translate
        StartForm.setWindowTitle(_translate("StartForm", "Form"))
        self.Sigma.setText(_translate("StartForm", "Sigma:10"))
        self.Size.setText(_translate("StartForm", "Kernel size: 2"))
        self.BackBtn.setText(_translate("StartForm", "Back"))
        self.GoBtn.setText(_translate("StartForm", "Reblur"))
        self.NextBtn.setText(_translate("StartForm", "Next"))
