# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'third.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from UI import QtExp

class Ui_StartForm(object):
    def setupUi(self, StartForm):
        StartForm.setObjectName("StartForm")
        StartForm.resize(625, 493)
        self.verticalLayout = QtWidgets.QVBoxLayout(StartForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(StartForm)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 588, 304))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Image = QtExp.ImageLabel(self.scrollAreaWidgetContents)
        self.Image.setMinimumSize(QtCore.QSize(0, 0))
        self.Image.setText("")
        self.Image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Image.setObjectName("Image")
        self.horizontalLayout.addWidget(self.Image)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.Low = QtWidgets.QLabel(StartForm)
        self.Low.setAlignment(QtCore.Qt.AlignCenter)
        self.Low.setObjectName("Low")
        self.verticalLayout.addWidget(self.Low)
        self.LowVal = QtWidgets.QSlider(StartForm)
        self.LowVal.setMaximum(300)
        self.LowVal.setProperty("value", 30)
        self.LowVal.setOrientation(QtCore.Qt.Horizontal)
        self.LowVal.setObjectName("LowVal")
        self.verticalLayout.addWidget(self.LowVal)
        self.High = QtWidgets.QLabel(StartForm)
        self.High.setAlignment(QtCore.Qt.AlignCenter)
        self.High.setObjectName("High")
        self.verticalLayout.addWidget(self.High)
        self.HighVal = QtWidgets.QSlider(StartForm)
        self.HighVal.setMaximum(300)
        self.HighVal.setProperty("value", 150)
        self.HighVal.setOrientation(QtCore.Qt.Horizontal)
        self.HighVal.setObjectName("HighVal")
        self.verticalLayout.addWidget(self.HighVal)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BackBtn = QtWidgets.QPushButton(StartForm)
        self.BackBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.BackBtn.setObjectName("BackBtn")
        self.horizontalLayout_3.addWidget(self.BackBtn)
        self.DoButton = QtWidgets.QPushButton(StartForm)
        self.DoButton.setMinimumSize(QtCore.QSize(0, 50))
        self.DoButton.setObjectName("DoButton")
        self.horizontalLayout_3.addWidget(self.DoButton)
        self.NextBtn = QtWidgets.QPushButton(StartForm)
        self.NextBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.NextBtn.setObjectName("NextBtn")
        self.horizontalLayout_3.addWidget(self.NextBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(StartForm)
        QtCore.QMetaObject.connectSlotsByName(StartForm)

    def retranslateUi(self, StartForm):
        _translate = QtCore.QCoreApplication.translate
        StartForm.setWindowTitle(_translate("StartForm", "Form"))
        self.Low.setText(_translate("StartForm", "Low Treshold: 30"))
        self.High.setText(_translate("StartForm", "High Treshold:150"))
        self.BackBtn.setText(_translate("StartForm", "Back"))
        self.DoButton.setText(_translate("StartForm", "ReLine"))
        self.NextBtn.setText(_translate("StartForm", "Next"))
